sdatg

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -42,10 +42,11 @@ jobs:
       - uses: actions/checkout@v4
       - name: Log in to Docker Hub
         env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Use the secret for your Docker username
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Use the secret for your Docker password
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
         run: |
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+          if [ $? -ne 0 ]; then echo "Docker login failed"; exit 1; fi
       - name: Build Docker image
         run: |
           docker build -t my-docker-image:latest .
